const projectDetails = [
    {
        id: 1,
        title: "Youtube Clone",
        purpose: "personal learning",
        overview: "Built a YouTube clone project using React.js and Redux, featuring a hamburger menu, search functionality with search suggestions, and live streaming.",
        keyFeature: "Hamburger Menu: ",
        description: "Implemented a responsive hamburger menu using React.js and tailwindcss, providing easy navigation for users.",
        secondkeyFeature: "Search Functionality:",
        secondDescription: "Developed a search feature with autocomplete suggestions, allowing users to quickly find their favorite videos or channels.",
        thirdkeyFeature: "Live Streaming: ",
        thirdDescription: "Integrated live streaming capabilities, enabling users to view real-time video updates.",
        technicalDetails1: "React.js: ",
        technicalDetails2: "Redux",
        tech_des: "Implemented Redux to manage application state and ensure seamless data flow.",
    },
    {
        id: 2,
        title: "Swiggy Clone",
        purpose: "personal learning",
        overview: "My Swiggy clone project is a web-based food delivery application that allows users to browse restaurants, add and delete food items to cart. I built this project using React.js for the frontend, Redux for managing the cart functionality and tailwind css for styling.Additionally, I implemented shimmer effects while API calls are in progress, a top-rated restaurants button, and lazy loading optimization to enhance the user experience.",
        keyFeature: "Restaurant Listings: ",
        description: "Users can browse through a list of restaurants and view their menus.",
        secondkeyFeature: "Food Item Addition: ",
        secondDescription: "Users can add food items to their cart.",
        thirdkeyFeature: "Cart Management: ",
        thirdDescription: "Users can view and manage their cart items.",
        fourthkeyFeature: "Shimmer Effects: ",
        fourthkeyDescription: "Shimmer effects are displayed while API calls is in progress to improve user experience. ",
        technicalDetails1: "React.js: ",
        technicalDetails2: "Redux",
        tech_des: "Implemented Redux to manage application state and ensure seamless data flow.",
 
    },
    {
        id: 3,
        title: "Tic-Tac-Toe Game",
        purpose: "personal learning",
        overview: "My Tic Tac Toe game project is a web-based implementation of the classic game, built using React.js. The game allows two players to play against each other, with the option to restart the game at any time.",
        keyFeature: "Game Board: ",
        description: "Displays the game state.",
        secondkeyFeature: "Player Turns: ",
        secondDescription: "Players take turns marking a square on the board with their symbol (X or O).",
        thirdkeyFeature: "Winning Conditions: ",
        thirdDescription: "The game checks for winning conditions after each turn and declares a winner.",
        fourthkeyFeature: "Restart: ",
        fourthkeyDescription: "A button to restart the game at any time.",
        technicalDetails1: "React.js: ",
        tech_des: "I used React.js to build the game.",
    },
    {
        id: 4,
        title: "Meme Generator ",
        purpose: "personal learning",
        overview: "My Meme Generator project is a web-based application that allows users to create and customize memes using React.js. The application provides a user-friendly interface to select a meme template, add text, and download the generated meme.",
        keyFeature: " Meme Templates: ",
        description: "A collection of pre-designed meme templates that users can select from.",
        secondkeyFeature: "Text Input:  ",
        secondDescription: "Users can add custom text to the selected meme template.",
        thirdkeyFeature: "Image Generation: ",
        thirdDescription: "The application generates a meme image with the user's text and selected template.",
        fourthkeyFeature: "Download: ",
        fourthkeyDescription: "Users can download the generated meme image.",
        technicalDetails1: "React.js: ",
        tech_des: "I used React.js to build this web application.",
    },
    {
        id: 5,
        title: "CRUD operations ",
        purpose: "personal learning",
        overview: "Built a CRUD operation project using React.js, demonstrating my ability to create, read, update, and delete data in a web application. The project showcases my understanding of React.js fundamentals, including components, state management, and data manipulation.",
        keyFeature: "Create",
        description: "Allows users to add new records or entries to a database.",
        secondkeyFeature: "Read",
        secondDescription: "Enables users to view or fetch existing data from the database.",
        thirdkeyFeature: "Update",
        thirdDescription: "Allows users to edit or update the details of existing records.",
        fourthkeyFeature: "Delete",
        fourthkeyDescription: "Provides functionality to delete specific records from the database.",
    },
    {
        id: 6,
        title: "Currency Converter ",
        purpose: "personal learning",
        overview: "My currency converter project is a web-based application that allows users to convert amounts between different currencies. The application uses JavaScript to fetch current exchange rates, perform calculations, and display the converted amounts.",
        keyFeature: "Currency Selection: ",
        description: "Users can select the source and target currencies from a dropdown list.",
        secondkeyFeature: "Amount Input:",
        secondDescription: "Users can input the amount they want to convert.",
        thirdkeyFeature: "Exchange Rate Fetching:",
        thirdDescription: "The application uses JavaScript to fetch current exchange rates from a reliable API.",
        fourthkeyFeature: "Calculation & Result Display: ",
        fourthkeyDescription: "The application performs the conversion calculation using the fetched exchange rates. and the converted amount is displayed to the user.",
        technicalDetails1: "JavaScript, HTML and CSS ",
        
    },
];

export default projectDetails;